src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ChangeEmail.cshtml.cs
using FamilyHub.IdentityServerHost.Models.Entities;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using System.ComponentModel.DataAnnotations;
using System.Text.Encodings.Web;
using System.Text;

namespace FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount;

public class ChangeEmailModel : PageModel
{
    private readonly UserManager<ApplicationIdentityUser> _userManager;
    private readonly SignInManager<ApplicationIdentityUser> _signInManager;
    private readonly IEmailSender _emailSender;

    public ChangeEmailModel(
        UserManager<ApplicationIdentityUser> userManager,
        SignInManager<ApplicationIdentityUser> signInManager,
        IEmailSender emailSender)
    {
        _userManager = userManager;
        _signInManager = signInManager;
        _emailSender = emailSender;
    }

    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public string Email { get; set; } = default!;

    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public bool IsEmailConfirmed { get; set; } = default!;


    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    [TempData]
    public string StatusMessage { get; set; } = default!;


    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    [BindProperty]
    public InputModel Input { get; set; } = default!;


    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public class InputModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [Required]
        [EmailAddress]
        [Display(Name = "New email")]
        public string NewEmail { get; set; } = default!;

    }

    public bool ValidationValid { get; set; } = true;

    private async Task LoadAsync(ApplicationIdentityUser user)
    {
        var email = await _userManager.GetEmailAsync(user);
        Email = email;

        Input = new InputModel
        {
            NewEmail = email,
        };

        IsEmailConfirmed = await _userManager.IsEmailConfirmedAsync(user);
    }

    public async Task<IActionResult> OnGetAsync()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
        }

        await LoadAsync(user);
        return Page();
    }

    public async Task<IActionResult> OnPostChangeEmailAsync()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
        }

        ValidationValid = ModelState.IsValid;
        if (!ModelState.IsValid)
        {
            await LoadAsync(user);
            return Page();
        }

        var email = await _userManager.GetEmailAsync(user);
        if (Input.NewEmail != email)
        {
            var userId = await _userManager.GetUserIdAsync(user);
            var code = await _userManager.GenerateChangeEmailTokenAsync(user, Input.NewEmail);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            var callbackUrl = Url.Page(
                "/Account/ConfirmEmailChange",
                pageHandler: null,
                values: new { area = "Identity", userId = userId, email = Input.NewEmail, code = code },
                protocol: Request.Scheme);
            await _emailSender.SendEmailAsync(
                Input.NewEmail,
                "Confirm your email",
                $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl ?? string.Empty)}'>clicking here</a>.");

            StatusMessage = "Confirmation link to change email sent. Please check your email.";
            return RedirectToPage();
        }

        StatusMessage = "Your email is unchanged.";
        return RedirectToPage();
    }

    public async Task<IActionResult> OnPostSendVerificationEmailAsync()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
        }

        ValidationValid = ModelState.IsValid;
        if (!ModelState.IsValid)
        {
            await LoadAsync(user);
            return Page();
        }

        var userId = await _userManager.GetUserIdAsync(user);
        var email = await _userManager.GetEmailAsync(user);
        var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
        code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
        var callbackUrl = Url.Page(
            "/Account/ConfirmEmail",
            pageHandler: null,
            values: new { area = "Identity", userId = userId, code = code },
            protocol: Request.Scheme);
        await _emailSender.SendEmailAsync(
            email,
            "Confirm your email",
            $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl ?? string.Empty)}'>clicking here</a>.");

        StatusMessage = "Verification email sent. Please check your email.";
        return RedirectToPage();
    }
}

src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ChangeName.cshtml.cs
using FamilyHub.IdentityServerHost.Models.Entities;
using FamilyHub.IdentityServerHost.Persistence.Repository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Build.Framework;

namespace FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount;

public class ChangeNameModel : PageModel
{
    private readonly UserManager<ApplicationIdentityUser> _userManager;
    private readonly IApplicationDbContext _applicationDbContext;

    [BindProperty]
    [Required]
    public string Username { get; set; } = default!;

    public string StatusMessage { get; set; } = default!;
    public bool ValidationValid { get; set; } = true;

    public ChangeNameModel(UserManager<ApplicationIdentityUser> userManager, IApplicationDbContext applicationDbContext)
    {
        _userManager = userManager;
        _applicationDbContext = applicationDbContext;
    }
    public async Task<IActionResult> OnGet()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
        }

        Username = _applicationDbContext.GetFullName(user.Email) ?? string.Empty;
        if (string.IsNullOrEmpty(Username)) 
        {
            Username = await _userManager.GetUserNameAsync(user);
        }   
            

        return Page();
    }

    public async Task<IActionResult> OnPost()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
        }

        ValidationValid = ModelState.IsValid;
        if (!ModelState.IsValid) 
        {
            return Page();
        }

        if (!await _applicationDbContext.SetFullNameAsync(user.Email, Username))
        {
            StatusMessage = "Error changing user name.";
            return Page();
        }

        return RedirectToPage("/MyAccount/ConfirmNameChanged", new
        {
            area = "Gds",
        });
    }
}

src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ChangePassword.cshtml.cs
using FamilyHub.IdentityServerHost.Models.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount;

public class ChangePasswordModel : PageModel
{
    private readonly UserManager<ApplicationIdentityUser> _userManager;
    private readonly SignInManager<ApplicationIdentityUser> _signInManager;
    private readonly ILogger<ChangePasswordModel> _logger;

    public ChangePasswordModel(
        UserManager<ApplicationIdentityUser> userManager,
        SignInManager<ApplicationIdentityUser> signInManager,
        ILogger<ChangePasswordModel> logger)
    {
        _userManager = userManager;
        _signInManager = signInManager;
        _logger = logger;
    }

    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    [BindProperty]
    public InputModel Input { get; set; } = default!;

    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    [TempData]
    public string StatusMessage { get; set; } = default!;

    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public class InputModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; } = default!;

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 8)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; } = default!;

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; } = default!;
    }

    public async Task<IActionResult> OnGetAsync()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
        }

        var hasPassword = await _userManager.HasPasswordAsync(user);
        if (!hasPassword)
        {
            return RedirectToPage("/Account/SetPassword", new
            {
                area = "Identity",
            });
            
        }

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
        }

        var changePasswordResult = await _userManager.ChangePasswordAsync(user, Input.OldPassword, Input.NewPassword);
        if (!changePasswordResult.Succeeded)
        {
            foreach (var error in changePasswordResult.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return Page();
        }

        await _signInManager.RefreshSignInAsync(user);
        _logger.LogInformation("User changed their password successfully.");
        StatusMessage = "Your password has been changed.";

        return RedirectToPage("/MyAccount/ConfirmPasswordChanged", new
        {
            area = "Gds",
        });
    }
}

src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ConfirmEmailChanged.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount
{
    public class ConfirmEmailChangedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ConfirmNameChanged.cshtml.cs
using FamilyHub.IdentityServerHost.Models.Entities;
using FamilyHub.IdentityServerHost.Persistence.Repository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount
{
    public class ConfirmNameChangedModel : PageModel
    {
        private readonly UserManager<ApplicationIdentityUser> _userManager;
        private readonly IApplicationDbContext _applicationDbContext;

        public string Username { get; set; } = string.Empty;

        public ConfirmNameChangedModel(UserManager<ApplicationIdentityUser> userManager, IApplicationDbContext applicationDbContext)
        {
            _userManager = userManager;
            _applicationDbContext = applicationDbContext;
        }
        public async Task<IActionResult> OnGet()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            Username = _applicationDbContext.GetFullName(user.Email) ?? string.Empty;
            if (string.IsNullOrEmpty(Username))
            {
                Username = await _userManager.GetUserNameAsync(user);
            }

            return Page();
        }
    }
}

src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ConfirmPasswordChanged.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount
{
    public class ConfirmPasswordChangedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ViewPersonalDetails.cshtml.cs
using FamilyHub.IdentityServerHost.Models.Entities;
using FamilyHub.IdentityServerHost.Persistence.Repository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount;

public class ViewPersonalDetailsModel : PageModel
{
    private readonly UserManager<ApplicationIdentityUser> _userManager;
    private readonly IApplicationDbContext _applicationDbContext;

    public string Username { get; set; } = default!;
    public string Email { get; set; } = default!;

    public ViewPersonalDetailsModel(UserManager<ApplicationIdentityUser> userManager, IApplicationDbContext applicationDbContext)
    {
        _userManager = userManager;
        _applicationDbContext = applicationDbContext;
    }
    public async Task<IActionResult> OnGet()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user == null)
        {
            return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
        }

        Username = _applicationDbContext.GetFullName(user.Email) ?? string.Empty;
        if (string.IsNullOrEmpty(Username)) 
        {
            Username = await _userManager.GetUserNameAsync(user);
        }
        
        Email = await _userManager.GetEmailAsync(user);

        return Page();
    }
}

src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ChangeEmail.cshtml
@page
@model FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount.ChangeEmailModel
@{
}

<a asp-page="/MyAccount/ViewPersonalDetails" class="govuk-back-link" data-testid="back-button">Back</a>

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">

    @if (Model?.ValidationValid == false)
    {
        <div class="govuk-error-summary" aria-labelledby="error-summary-title" role="alert" data-module="govuk-error-summary">
            <h2 class="govuk-error-summary__title" id="error-summary-title">
                There is a problem
            </h2>
            <div class="govuk-error-summary__body">
                <ul class="govuk-list govuk-error-summary__list">
                    <li>
                        <a href="#" data-testid="enter-organisation-name-error">Enter an emaill address in the correct format</a>
                    </li>
                </ul>
            </div>
        </div>
    }

    <fieldset class="govuk-fieldset">
      <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
        <span class="govuk-fieldset__heading">
          Change your email address
        </span>
      </legend>
      <form method="post" data-validate='my-form-validation'>
        <partial name="_StatusMessage" model="Model?.StatusMessage" />
        
        @if (Model?.ValidationValid == false)
        {
            <p class="govuk-error-message">
                <span class="govuk-visually-hidden" data-testid="name-enter-validation">Error:</span>
                <span asp-validation-for="Input.NewEmail"></span>
            </p>
        }

        <div class="govuk-form-group"> <label for="new-email" class="govuk-label">Email</label>
         <input type="email" asp-for="Input.NewEmail" class="govuk-input govuk-!-width-one-half" autocomplete="new-email" value="@Model?.Email">
        </div>
        <button type="submit" asp-page-handler="ChangeEmail" class="govuk-button">
          Continue
        </button>
      </form>
        <p><a asp-page="/MyAccount/ViewPersonalDetails">Cancel</a></p>
    </fieldset>
</main>

src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ChangeName.cshtml
@page
@model FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount.ChangeNameModel
@{
}

<a asp-page="/MyAccount/ViewPersonalDetails" class="govuk-back-link" data-testid="back-button">Back</a>

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">

    @if (Model?.ValidationValid == false)
    {
        <div class="govuk-error-summary" aria-labelledby="error-summary-title" role="alert" data-module="govuk-error-summary">
            <h2 class="govuk-error-summary__title" id="error-summary-title">
                There is a problem
            </h2>
            <div class="govuk-error-summary__body">
                <ul class="govuk-list govuk-error-summary__list">
                    <li>
                        <a href="#" data-testid="enter-organisation-name-error">Enter a name</a>
                    </li>
                </ul>
            </div>
        </div>
    }

    <partial name="_StatusMessage" model="Model?.StatusMessage" />
    <fieldset class="govuk-fieldset">
      <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
        <span class="govuk-fieldset__heading">
          Change your name
        </span>
      </legend>
      <form method="post" data-validate='my-form-validation'>
       @if (Model?.ValidationValid == false)
        {
            <p class="govuk-error-message">
                <span class="govuk-visually-hidden" data-testid="name-enter-validation">Error:</span>
                    <span asp-validation-for="Username"></span>
            </p>
        }
        <div class="govuk-form-group"> <label for="new-name" class="govuk-label">Name</label>
            <input type="text" asp-for="Username" class="govuk-input govuk-!-width-one-half" autocomplete="Username" value="@Model?.Username">    
        </div>

        <button class="govuk-button">
          Continue
        </button>
      </form>
      <p><a asp-page="/MyAccount/ViewPersonalDetails">Cancel</a></p>
    </fieldset>
</main>

src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ChangePassword.cshtml
@page
@model FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount.ChangePasswordModel
@{
}

<a asp-page="/MyAccount/ViewPersonalDetails" class="govuk-back-link" data-testid="back-button">Back</a>

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">
    <fieldset class="govuk-fieldset">
      <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
        <span class="govuk-fieldset__heading">
          Change your password
        </span>
      </legend>
      <form method="post" novalidate data-validate='my-form-validation'>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <partial name="_StatusMessage" model="Model.StatusMessage" />
            <div class="govuk-form-group">
                <label for="Input.OldPassword" class="govuk-label">Current password</label>
                <input type="password" asp-for="Input.OldPassword" class="govuk-input govuk-!-width-one-half" autocomplete="current-password">
                <span asp-validation-for="Input.OldPassword" class="text-danger"></span>
            </div>
            <div class="govuk-form-group">
                <label for="Input.NewPassword" class="govuk-label">New password</label>
                <input type="password" asp-for="Input.NewPassword" class="govuk-input govuk-!-width-one-half" autocomplete="new-password">
                <span asp-validation-for="Input.NewPassword" class="text-danger"></span>
            </div>
            <div class="govuk-form-group">
                <label for="Input.ConfirmPassword" class="govuk-label">Confirm new password</label>
                <input type="password" asp-for="Input.ConfirmPassword" class="govuk-input govuk-!-width-one-half" autocomplete="confirm-password">
                <span asp-validation-for="Input.ConfirmPassword" class="text-danger"></span>
            </div>
        <button type="submit" class="govuk-button">
          Continue
        </button>
      </form>
        <p><a asp-page="/MyAccount/ViewPersonalDetails">Cancel</a></p>
      <script type="application/json" id="my-form-validation">

        {
          "current-password": {
            "presence": {
              "message": "^Enter your current password"
            }
          },
          "new-password": {
            "presence": {
              "message": "^Enter a new password"
            }
          },
          "confirm-password": {
            "presence": {
              "message": "^Confirm your new password"
            },
            "equality": {
              "attribute": "new-password",
              "message": "^Passwords do not match"
            }
          }
        }
      </script>
    </fieldset>
</main>

src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ConfirmEmailChanged.cshtml
@page
@model FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount.ConfirmEmailChangedModel
@{
}

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">
 <h1 class="govuk-heading-l">We have sent you a link to confirm your new email address</h1>
 <p>Click on the link in the email to confirm your new email address. Once you have confirmed, your new email address will be linked to your account.</p>
 <a class="govuk-button" asp-page="/MyAccount/ViewPersonalDetails">Go to homepage</a>
</main>

src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ConfirmNameChanged.cshtml
@page
@model FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount.ConfirmNameChangedModel
@{
}

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">
    <h1 class="govuk-heading-l">Your name has been changed</h1>
    <p>Your account name is now changed to @Model.Username.</p>
    <a class="govuk-button" asp-page="/MyAccount/ViewPersonalDetails">Go to homepage</a>
</main>

src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ConfirmPasswordChanged.cshtml
@page
@model FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount.ConfirmPasswordChangedModel
@{
}

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">
    <h1 class="govuk-heading-l">Your password has been changed</h1>
    <p>Your account password is now changed.</p>
    <a class="govuk-button" asp-page="/MyAccount/ViewPersonalDetails">Go to homepage</a>
</main>

src/FamilyHub.IdentityServerHost/Areas/Gds/Pages/MyAccount/ViewPersonalDetails.cshtml
@page
@model FamilyHub.IdentityServerHost.Areas.Gds.Pages.MyAccount.ViewPersonalDetailsModel
@{
}

<a asp-page="/Manage/Homepage" class="govuk-back-link" data-testid="back-button">Back</a>

<main class="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">
    <fieldset class="govuk-fieldset">
      <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
        <span class="govuk-fieldset__heading">
          Manage your account
        </span>
      </legend>
      <table class="govuk-table govuk-!-margin-top-2">
        <tbody class="govuk-table__body">
        <tr class="govuk-table__row">
          <th scope="row" class="govuk-table__header">Name</th>
          <td class="govuk-table__cell">@Model.Username</td>
          <td class="govuk-table__cell govuk-table__cell--numeric"><a asp-page="/MyAccount/ChangeName">Change</a></td>
        </tr>
        <tr class="govuk-table__row">
          <th scope="row" class="govuk-table__header">Email address</th>
          <td class="govuk-table__cell">@Model.Email</td>
          <td class="govuk-table__cell govuk-table__cell--numeric"><a asp-page="/MyAccount/ChangeEmail">Change</a></td>
        </tr>
        <tr class="govuk-table__row">
          <th scope="row" class="govuk-table__header">Password</th>
          <td class="govuk-table__cell">Change your current password</td>
          <td class="govuk-table__cell govuk-table__cell--numeric"><a asp-page="/MyAccount/ChangePassword">Change</a></td>
        </tr>
        </tbody>
      </table>
    </fieldset>
</main>